version: '3.4'

services:
  traefik:
    image: traefik
    command: --api --docker
    container_name: traefik
    ports:
      - "80:80" #All HTTP access will be caught by Traefik
      - "443:443" #All HTTPS access will be caught by Traefik
      - "8080:8080" #Access Traefik webview
    networks:
      - web
    labels:
      # Make sure this domain points to your IP so that traefik can request a cert
      - traefik.frontend.rule=Host:traefik.localhost
      # Traefik will proxy to its own GUI
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  web:
    external: true
